### ISSUE TITLE
Missing dependency: django-appconf

### ISSUE THREAD

**Issue by melbic** [dreipol/djangocms-spa#3]
* djangocms_spa version: 0.1.15
* Django version: 1.10
* Python version: 3.5
* Operating System: macOS 10.12

### Description
I tried to add `djangocms-spa` as described. Unfortunately the package has a missing dependency: `django-appconf`

### Quickfix
```
pip install django-appconf==1.0.2
```

### Todo
Add dependency to pypi package.

**Comment by chschuermann** [comment]
Thanks for submitting this issue. We just added the missing requirement in https://github.com/dreipol/djangocms-spa/commit/9c9b26da1a86489c1f73c5ffe9961401c32bca45.
